In [1]:
print('Bismillah')

Bismillah


In [2]:
print('NUMPY PRACTICES')

NUMPY PRACTICES


In [3]:
import numpy as np #  Numpy Libarary Import 

In [50]:
#  Array_Zeros, Array_Ones, Array_Empty , Array_Identity --> np.zeros,np.zeros,zp.empty,np.eye

In [8]:
array_one = np.array([1,2,3,4,5]) 

In [9]:
array_one

array([1, 2, 3, 4, 5])

In [10]:
type(array_one)

numpy.ndarray

In [11]:
list1 = ['a','b','c','d']

In [12]:
print(list1)

['a', 'b', 'c', 'd']


In [13]:
type(list1)

list

In [14]:
np.array1 = np.array(list1) # passing list as array

In [15]:
np.array1

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [17]:
type(np.array1) 

numpy.ndarray

In [18]:
array_ones = np.ones((3,4))  # Ones Array

In [19]:
array_ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
array_zeros= np.zeros((3,4)) # Zeros Array

In [26]:
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
array_onesint = np.ones((2,2),dtype=np.int16) # Type Conversion from float to int 

In [32]:
array_onesint

array([[1, 1],
       [1, 1]], dtype=int16)

In [38]:
array_empty = np.empty((2,2),dtype=np.int16) # Empty Array

In [39]:
array_empty

array([[-256,   -1],
       [   0,    2]], dtype=int16)

In [46]:
array_identity = np.eye((3),dtype = np.int16) #  Identity Matrix

In [47]:
array_identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [49]:
#  1d_array , 2d_array , 3d_array , range --> np.arange(1,10,2), np.array([1,2],[3,4]) , np.array

In [57]:
one_d_array = np.array([1,2,3]) # 1d array

In [58]:
one_d_array

array([1, 2, 3])

In [59]:
type(one_d_array)

numpy.ndarray

In [62]:
one_d_array2 = np.arange(4)

In [63]:
one_d_array2 # 1 d array using arange

array([0, 1, 2, 3])

In [64]:
one_d_array3 = np.arange(1,10,2) # 1d array using range interval 

In [65]:
one_d_array3

array([1, 3, 5, 7, 9])

In [82]:
two_d_array = np.array([(1,2),(3,4)]) # 2d array

In [75]:
two_d_array

array([[1, 2],
       [3, 4]])

In [80]:
two_d_array2 = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [81]:
two_d_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
two_d_array2.shape

(3, 3)

In [85]:
type(two_d_array2)

numpy.ndarray

In [88]:
two_d_array3 = np.arange(6).reshape(2,3) # 2d array using range and reshape

In [89]:
two_d_array3

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
three_d_array = np.arange(12).reshape(2,3,2)  # 3d array using range and reshape

In [91]:
three_d_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [93]:
three_d_array2 = np.array([[(1,2),(3,4)],[(5,6),(7,8)]])  # 3d array


In [94]:
three_d_array2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [97]:
three_d_array3 = np.array([[(1,2),(3,4)],[(5,6),(7,8)]])

In [98]:
three_d_array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
 # Numpy Arethmatic Operations

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([4,5,6])

In [5]:
b

array([4, 5, 6])

In [6]:
a+b

array([5, 7, 9])

In [7]:
a-b

array([-3, -3, -3])

In [8]:
a*b

array([ 4, 10, 18])

In [9]:
a/b

array([0.25, 0.4 , 0.5 ])

In [10]:
a%b

array([1, 2, 3])

In [13]:
c=np.arange(6).reshape(2,3)

In [14]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
d = np.array([[1,2,3],[4,5,6]])

In [17]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c+d

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [22]:
d.shape

(2, 3)

In [23]:
a+b*c/d  # when we add 1,2 martix to 2,2 matrix , its taking 1,2 matrix as 2,2 martix with the same value on row1

array([[1. , 4.5, 7. ],
       [4. , 6. , 8. ]])

In [24]:
a+d

array([[2, 4, 6],
       [5, 7, 9]])

In [26]:
e=a+b

In [27]:
e

array([5, 7, 9])

In [28]:
e>a

array([ True,  True,  True])

In [29]:
a>b

array([False, False, False])

In [30]:
b>a

array([ True,  True,  True])

In [31]:
a

array([1, 2, 3])

In [32]:
b

array([4, 5, 6])

In [33]:
e>a+b

array([False, False, False])

In [34]:
e>=a+b

array([ True,  True,  True])

In [35]:
e<=a+b

array([ True,  True,  True])

In [36]:
a**2  # SQUARE 

array([1, 4, 9])

In [37]:
a**3  #  CUBE 

array([ 1,  8, 27])

In [39]:
a**1

array([1, 2, 3])

In [ ]:
  # Updating old value 

In [57]:
a

array([ 60, 100, 140])

In [41]:
a*=2

In [68]:
a

array([120, 200, 280])

In [73]:
a=a*(1/10)

In [74]:
a

array([12., 20., 28.])

In [75]:
a+=10

In [76]:
a

array([22., 30., 38.])

In [77]:
a-=10

In [78]:
a

array([12., 20., 28.])

In [79]:
 # Unary Operations

In [80]:
min(a)

12.0

In [81]:
max(a)

28.0

In [82]:
sum(a)

60.0

In [87]:
a.min()

12.0

In [88]:
a

array([12., 20., 28.])

In [89]:
a.max()

28.0

In [90]:
a.sum()

60.0

In [91]:
a.mean()

20.0

In [92]:
 # Statistical Functions

In [93]:
a

array([12., 20., 28.])

In [95]:
a.mean() # average

20.0

In [101]:
x=np.arange(6).reshape(2,3)

In [102]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
x.sum()

15

x.sum(axis=0) # Axis 0 for column sum 

In [104]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
x.sum(axis=1) # for Row level sum 

array([ 3, 12])

In [107]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [133]:
x.mean()

2.5

In [130]:
mean = np.mean(x)

In [125]:
median = np.median(x)  #  for median np. is mandatory

In [118]:
x.mean()

2.5

In [126]:
standard_deviation = np.std(x)  # standard deviation

In [127]:
varience = np.var(x) # varience

In [156]:
print ('mean = %i ' %mean)  # i is the possible place holder to use 

mean = 2 


In [144]:
print('median = %i' %median)

median = 2


In [146]:
print('std = %i' % standard_deviation)

std = 1


In [155]:
print ('varience is %i' %varience)

varience is 2


In [158]:
 # Looping using Numpy

In [176]:
y = np.arange(11)

In [177]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
z = np.arange(11)**2


In [181]:
z

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [192]:
for i in z:
    print(f"The actual price is {i}")
    print ("Discounted price is",i/2, "\n")

The actual price is 0
Discounted price is 0.0 

The actual price is 1
Discounted price is 0.5 

The actual price is 4
Discounted price is 2.0 

The actual price is 9
Discounted price is 4.5 

The actual price is 16
Discounted price is 8.0 

The actual price is 25
Discounted price is 12.5 

The actual price is 36
Discounted price is 18.0 

The actual price is 49
Discounted price is 24.5 

The actual price is 64
Discounted price is 32.0 

The actual price is 81
Discounted price is 40.5 

The actual price is 100
Discounted price is 50.0 



In [193]:
 # Looping in mutidimensional array

In [194]:
m = np.arange(12).reshape(3,4)

In [195]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [203]:
for k in m :
    print(k)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [204]:
for k in m :
    print('muti dimesion array looping in row level : ' , k)

muti dimesion array looping in row level :  [0 1 2 3]
muti dimesion array looping in row level :  [4 5 6 7]
muti dimesion array looping in row level :  [ 8  9 10 11]


In [206]:
for k in m.flatten():
    print('multi dimensional looping in cell level', k)

multi dimensional looping in cell level 0
multi dimensional looping in cell level 1
multi dimensional looping in cell level 2
multi dimensional looping in cell level 3
multi dimensional looping in cell level 4
multi dimensional looping in cell level 5
multi dimensional looping in cell level 6
multi dimensional looping in cell level 7
multi dimensional looping in cell level 8
multi dimensional looping in cell level 9
multi dimensional looping in cell level 10
multi dimensional looping in cell level 11


In [199]:
n = m.flatten()

In [200]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [202]:
for j in n :
    print (j)

0
1
2
3
4
5
6
7
8
9
10
11


In [207]:
m 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [212]:
j = m.flatten()

In [213]:
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [214]:
l = m.flatten(order='f')

In [216]:
l  #  compare the difference between j and l , order = 'f' for Forton to flatten by Column level

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [218]:
 #  Nditer

m

In [219]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [223]:
m.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [230]:
import numpy as np

In [231]:
np.nditer(m)

In [240]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
x = np.nditer(a)
print(x)

for u in np.nditer(a):
    print(u)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [241]:
# Nditer is working only with in For Loop for Flattern purpose 

In [242]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [247]:
for t in np.nditer(m, order = 'F'): # F should be capital F, for column based flattening
    print(t)

0
4
8
1
5
9
2
6
10
3
7
11


In [249]:
# Deep Copying Vs Shallow Copying -- only can be used on np.array values 
# Deep Copy is Copy -- used for less amount of data eg:1mb
# Shallow Copy is View -- used for larger amount of data eg:1tb

In [277]:
a = np.array([1,2,3,4,5]) 

In [278]:
a

array([1, 2, 3, 4, 5])

In [279]:
b = a.view() # Shallow Copying 

In [280]:
b

array([1, 2, 3, 4, 5])

In [281]:
a is b

False

In [282]:
a.base is b

False

In [283]:
b.base is a 

True

In [286]:
print(id(a))

4651739536


In [287]:
print(id(b))

4651787088


In [288]:
id(a) is id(b)

False

In [289]:
a is b

False

In [290]:
a.base is b

False

In [291]:
b.base is a 

True

In [302]:
b 

array([1, 2, 3, 4, 5])

In [305]:
b[0]=10 # Updating view 

In [306]:
b

array([10,  2,  3,  4,  5])

In [307]:
a  # Changes on view , refelcted on base array 

array([10,  2,  3,  4,  5])

In [ ]:
# View can be updated, the change will reflect on base array 

In [293]:
# Deep Copying 

In [322]:
c = np.array([1,2,3,4,5])

In [323]:
d = c.copy()

In [324]:
c

array([1, 2, 3, 4, 5])

In [325]:
d

array([1, 2, 3, 4, 5])

In [326]:
d is c 

False

In [327]:
d.base is c

False

In [328]:
d.base is c

False

In [329]:
c

array([1, 2, 3, 4, 5])

In [330]:
d

array([1, 2, 3, 4, 5])

In [331]:
id(c)

4651863696

In [332]:
id(d)

4651862416

In [333]:
d[0]= 100 # Updating Copy , it will NOT reflect on base 

In [334]:
d

array([100,   2,   3,   4,   5])

In [335]:
c

array([1, 2, 3, 4, 5])