In [1]:
print('Bismillah')
print('Day-4')

Bismillah
Day-4


In [ ]:
NUMPY - 
Numerical Computation
Scientific Computation
Highend Mathematical Operation

AI ML DA 

In [ ]:
Numpy deals with N- Dimensional Arryas
Array - More Optimized and efficient than list 

In [2]:
!pip install numpy

In [3]:
!pip install numpy --upgrade

     |████████████████████████████████| 15.1 MB 658 kB/s eta 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
      Successfully uninstalled numpy-1.18.1


In [13]:
import numpy as np

In [14]:
array_one = np.zeros((2,2))

In [15]:
print('check')

check


In [16]:
array_one

array([[0., 0.],
       [0., 0.]])

In [21]:
array_ones = np.ones((3,4))

In [22]:
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
array_zeros = np.zeros((2,3))

In [29]:
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Befault array datatype is flot , thats why getting .

In [31]:
array1 = np.array([1,2,3,4,5])

In [32]:
array1

array([1, 2, 3, 4, 5])

In [35]:
array2=np.array(['a','b','c','d','f'])

In [36]:
array2

array(['a', 'b', 'c', 'd', 'f'], dtype='<U1')

In [37]:
type(array2)

numpy.ndarray

In [38]:
type(array1)

numpy.ndarray

In [39]:
array3 = np.array([1,2,3,4,5])

In [40]:
array3

array([1, 2, 3, 4, 5])

In [43]:
array_zeros = np.zeros((3,2),dtype=np.int16)

In [44]:
array_zeros

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [45]:
print(array_zeros)

[[0 0]
 [0 0]
 [0 0]]


In [52]:
array_ones = np.ones((3,3),dtype=np.int16)

In [53]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [54]:
print(array_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
